import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="stylesheet" type="text/css" href="/assets/css/loaders/loader.min.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/plugins.min.css" />
        <link rel="stylesheet" type="text/css" href="/assets/css/main.min.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
